config/routes.rb
Flix::Application.routes.draw do

resource :session

get 'signup' => 'users#new'
get "signin" => "sessions#new"

  resources :users

  root "movies#index"
  resources :movies do 
  	  resources :reviews
  end

end

app/models/movie.rb
class Movie < ActiveRecord::Base
mount_uploader :image_file_name, ImageUploader

validates :title, :released_on, :duration, presence: true
validates :description, length: { minimum: 25 }
validates :total_gross, numericality: { greater_than_or_equal_to: 0 }
# validates :image_file_name, allow_blank: true, format: {
#   with:    /\w+.(gif|jpg|png)\z/i,
#   message: "must reference a GIF, JPG, or PNG image"
# }
RATINGS = %w(G PG PG-13 R NC-17 AO)
validates :rating, inclusion: { in: RATINGS }
has_many :reviews, dependent: :destroy

  def self.released
    where("released_on <= ?", Time.now).order("released_on desc")
  end
  
  def self.hits
    where('total_gross >= 300000000').order('total_gross desc')
  end
  
  def self.flops
    where('total_gross < 10000000').order('total_gross asc')
  end
  
  def self.recently_added
    order('created_at desc').limit(3)
  end
  
  def flop?
    total_gross.blank? || total_gross < 50000000
  end

  def average_stars
    reviews.average(:stars)
  end

  def recent_reviews
    reviews.order("created_at desc")
  end

 

end

app/models/review.rb
class Review < ActiveRecord::Base

validates :name, presence: true
validates :comment, length: { minimum: 4 }

STARS = [1, 2, 3, 4, 5]

validates :stars, inclusion: { 
  in: STARS,
  message: "must be between 1 and 5"
}	
  belongs_to :movie

  def self.created
    where("created_at <= ?", Time.now).order("created_at desc")
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password  
  validates :name, presence: true
  validates :email, presence: true, 
  					format: /\A\S+@\S+\z/,
  					uniqueness: { case_sensitive: false }
  validates :username, presence: true,
                     format: /\A[A-Z0-9]+\z/i,
                     uniqueness: { case_sensitive: false }

  def self.authenticate(email_or_username , password)
  		u = User.find_by(username: email_or_username) || User.find_by(email: email_or_username)
  		u && u.authenticate(password) 
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

private

	def require_signin
		unless current_user
			session[:intended_url] = request.url
			redirect_to new_session_url, alert: "You have to sign in dude!!!"
		end
	end

	def current_user?(a)
		current_user == a
	end

	def logged_admin?
		current_user && current_user.admin?		
	end

	def current_user
	  	@current_user ||= User.find(session[:user_id]) if session[:user_id]  	
	end

  	def require_admin
      unless logged_admin?
        redirect_to root_path, alert: 'You are not the boss here, ask me (Akiro) 
                                        for admin priviledges you fool.'
      end
  	end

	helper_method :current_user
	helper_method :current_user?
	helper_method :logged_admin?
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
before_action :require_signin, except: [:show, :index]
before_action :require_admin, except: [:show, :index]

  def index
    @movies = Movie.released
    @image = ImageUploader.new
  end

  def show
    @movie = Movie.find(params[:id])
    @image = ImageUploader.new
  end
  
  def edit
    @movie = Movie.find(params[:id])
  end
  
  def update
    @movie = Movie.find(params[:id])
    if @movie.update(movie_params)
      redirect_to @movie, notice: "Movie successfully updated!"
    else
      render :edit
    end
  end

  def new
    @movie = Movie.new
  end
  
  def create
    @movie = Movie.new(movie_params)
    if @movie.save
      redirect_to @movie, notice: "Movie successfully created!"
    else
      render :new
    end
  end
  
  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    redirect_to movies_url, alert: "Movie successfully deleted!"
  end
  
private

  def movie_params
    params.require(:movie).permit(:title, :description, :rating, :released_on, 
                                  :total_gross, :cast, :director, :duration, :image_file_name)
  end


end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
before_action :movie_var


	def index
		  @reviews = (@movie.reviews).created
	end

	def new
		  @reviews = @movie.reviews.new
	end

  	def destroy
		  @reviews = @movie.reviews.find(params[:id])
		  @reviews.destroy
		  redirect_to movie_reviews_path(@movie), alert: "Review successfully deleted!"
  	end

	def create
		  @reviews = @movie.reviews.new(review_params)
		  if @reviews.save
		  redirect_to movie_reviews_path(@movie),
		  notice: 'Thanks for your review!'
		else
		  render :new
		end
	end

	def edit
  		 @reviews = @movie.reviews.find(params[:id])
	end
	
	def update
		 @reviews = @movie.reviews.find(params[:id])
	 	if @reviews.update(review_params)
		  redirect_to movie_reviews_path, notice: "Review successfully updated!"
		else
	    render :edit
	  	end
	end

	private

	def review_params
    params.require(:review).permit(:name, :stars, :comment)
  	end

  	def movie_var
		  @movie = Movie.find(params[:movie_id])
	end	  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new	
	end

	def create
		if 	u = User.authenticate(params[:usermail], params[:password]) 
		then
			session[:user_id] = u.id
			flash[:notice] = "Welcome back, #{u.name}!"
			redirect_to(session[:intended_url] || u)
			session[:intended_url] = nil
		else	
			flash.now[:alert] = "Incorrect password or username combination pal"
			render :new
		end
	end

	def destroy
		session[:user_id] = nil
		redirect_to root_url, notice: "Thank you, come again!"
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :require_signin, except: [:new, :create]
before_action :require_correct_user, only: [:edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
    @users = User.find(params[:id])
  end
  
  def edit
  end
  
  def update
    if @users.update(user_params)
      redirect_to @users, notice: "Account successfully updated!"
    else
      render :edit
    end
  end

  def new
    @users = User.new
  end
  
  def create
    @users = User.new(user_params)
    if @users.save
      session[:user_id] = @users.id
      redirect_to @users, notice: "Account successfully created!"
    else
      render :new
    end
  end
  
  def destroy
    @users.destroy
    session[:user_id] = nil
    redirect_to root_path, alert: "Account successfully deleted!"
  end
  
private

  def user_params
    params.require(:user).permit(:username, :name, :email, :password, :password_confirmation)
  end

  def require_correct_user
    @users = User.find(params[:id])
    unless current_user?(@users)
    redirect_to root_path, notice: 'That\'s not your account you rascal'
    end
  end


end

app/helpers/application_helper.rb
module ApplicationHelper


end

app/helpers/movies_helper.rb
module MoviesHelper
 def format_total_gross(movie)
   if movie.flop?
    content_tag(:strong, 'Flop!') + " it only made " + number_to_currency(movie.total_gross)
   else
     number_to_currency(movie.total_gross)
   end
 end
 


  def image_for(movie)
    if movie.image_file_name.blank?
      image_tag('placeholder.png')
    else
      link_to image_tag(movie.image_file_name.thumb.url), movie
   end
  end

  def format_average_stars(movie)
      if movie.average_stars.nil?
        content_tag(:strong, 'No reviews')
      else
        image_tag (movie.average_stars.to_i.to_s + '_stars.png')
    end
  end

 def edit_review_image
   image_tag('add2.png', style: 'border: 0', :title => 'Edit Review')
 end

 def delete_review_image
   image_tag('trash.png', style: 'border: 0', :title => 'Delete Review')
 end


          

end

app/helpers/reviews_helper.rb
module ReviewsHelper



end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flashes.html.erb
<% flash.each do |key, value| %>
  <%= content_tag(:p, value, :class => "flash #{key}") %>
<% end %>

app/views/layouts/_footer.html.erb
<footer id="page-footer">
  <p>
    Copyright &copy; 2014
    <%= link_to 'Akiro Semtei', 'http://akirosemtei.com' %>
  </p>
</footer>

app/views/layouts/_header.html.erb
<header id="page-header">
	<div id="mastheads">
		<h1><%= link_to 'Akiro Fabulous Flixs', root_path %></h1>
	</div>
	<div id="masthead2">
	<nav>
	    <% if current_user %>
	    	<strong>	<%=  link_to(current_user.name.upcase, current_user ) %>  &nbsp;</strong>
	    		    	<%= link_to 'Sign Out', session_path, method: :delete, 
	    				class: 'button ok review' %>

	    <% end %>
	</nav>
	</div> 
</header>

app/views/layouts/_sidebar.html.erb
<aside id="sidebar">
  <nav>
    <ul>
      <li class="all-movies">
        <%= link_to 'All Movies', movies_path, class: 'button' %>
      </li>
  <% if logged_admin? %>
      <li class="create-movie">
        <%= link_to 'Add New Movie', new_movie_path, class: 'button' %>
      </li>
  <% else %>
  <% end %>
  <% if current_user %>
  <% else %>
      <li class="sign-up">
        <%= link_to 'Sign Up', signup_path, class: 'button' %>
      </li>
      <li class="sign-in">
        <%= link_to 'Sign in', signin_path, class: 'button' %>
      </li>

  <% end %>

    </ul>
  </nav>
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Akiro's Favorite FLIX</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render "layouts/header" %>

<div id="wrapper">

<%= render "layouts/flashes" %>

  <div id="container">
    <section id="sidebar">
      <%= render "layouts/sidebar" %>
    </section>
    <section id="content">
      <%= yield %>
    </section>
  </div>

</div>

<%= render "layouts/footer" %>

</body>
</html>

app/views/movies/_form.html.erb
<%= form_for(@movie) do |f| %>
<%= render "shared/errors", object: @movie %>
  <fieldset>
    <ol>
      <li class="required">
        <%= f.label :title %>
        <%= f.text_field :title, autofocus: true %>
      </li>
      <li class="required">
        <%= f.label :description %>
        <%= f.text_area :description, cols: 40, rows: 7 %>
      </li>
      <li class="required">
        <%= f.label :rating %>
        <%= f.select :rating, Movie::RATINGS, prompt: "Pick one" %>
      </li>
      <li class="required">
        <%= f.label :released_on %>
        <%= f.date_field :released_on %>
      </li>
      <li class="required">
        <%= f.label :total_gross %>
        <%= f.number_field :total_gross %>
      </li>
      <li class="required">
        <%= f.label :duration %>
        <%= f.text_field :duration, size: 10 %>
      </li>
      <li>
        <%= f.label :cast %>
        <%= f.text_field :cast %>
      </li>
      <li>
        <%= f.label :director %>
        <%= f.text_field :director %>
      </li>
      <li class="required">
        <%= f.label :image_file_name %>
        <%= f.file_field :image_file_name %>
      </li>
    </ol>
    <p>
      <%= f.submit %>
      <%= link_to "Cancel", movies_path, class: 'button' %>
    </p>
  </fieldset>
<% end %>

app/views/movies/edit.html.erb
<header id="content-header">
  <h1>Editing <%= @movie.title %></h1>
</header>

<%= render 'form' %>

app/views/movies/index.html.erb
<ul id="movies">
  <% @movies.each do |movie| %>
    <li>
      <article class="movie">
        <header>
          <%= image_for(movie) %>
          <h2><%= link_to movie.title, movie %> (<%= movie.released_on.year %>)</h2>
          <h3><%= movie.cast %></h3>
        </header>
        <p>
          <%= truncate(movie.description, length: 150, separator: ' ') %>
        </p>
        <table>
          <tr>
            <th>Rating</th>
            <td><%= movie.rating %></td>
          </tr>
          <tr>
            <th>Duration</th>
            <td><%= movie.duration %></td>
          </tr>
          <tr>
            <th>Total Gross</th>
            <td><%= format_total_gross(movie) %></td>
          </tr>
        </table>
        <footer>
        </footer>
      </article>
    </li>
  <% end %>
</ul>

app/views/movies/new.html.erb
<header id="content-header">
  <h1>Create a New Movie</h1>
</header>

<%= render 'form' %>

app/views/movies/show.html.erb
<article id="movie" class="movie">




  <header>
    <%= image_tag(@movie.image_file_name.masthead.url) %>
    <h1><%= @movie.title %></h1>
    <h2>Released: <%= @movie.released_on %></h2>
  </header>

  <p>
    <%= @movie.description %>
  </p>
  
  <h3 class="no-rule">
    <%= @movie.rating %> &bull; <%= @movie.duration %> 
  </h3>
  
  <h3>Cast</h3>
  <p>
    <%= @movie.cast %>
  </p>
  
  <h3>Director</h3>
  <p>
    <%= @movie.director %>
  </p>
  
  <h3>Total Gross</h3>
  <p>
    <%= format_total_gross(@movie) %>
  </p>
  
  <footer>
    <nav>
      <%= link_to "Write Review", 
          new_movie_review_path(@movie), 
          class: 'button ok review' %> <br><br><br>
  <% if logged_admin? %>
      <%= link_to 'Edit', edit_movie_path(@movie),
          class: 'button' %>
      <%= link_to 'Delete', @movie, 
          class: 'button',
          method: :delete, data: { confirm: 'Are you sure?' } %>
  <% else %>
  <% end %>
      <%= link_to pluralize(@movie.reviews.size, "review"), 
          movie_reviews_path(@movie), 
          class: 'button' %>
    </nav>
  </footer>
</article>

app/views/reviews/_form.html.erb


<%= form_for([@movie, @reviews]) do |f| %>
<%= render "shared/errors", object: @reviews %>
  <fieldset>
    <ol>
      <li class="required">
        <%= f.label :name %>         
        <%= f.text_field :name, size: 40, autofocus: true %>
      </li>
      <li class="required stars">
        <%= f.label :stars %>  
        <%= f.select :stars, Review::STARS, prompt: "Pick one" %>      
      </li>
      <li class="required">
        <%= f.label :comment %>
        <%= f.text_area :comment, cols: 80, placeholder: "What did you think?" %>
      </li>
    </ol>
    <p>
      <%= f.submit creadit + ' Review' %> 
      <%= link_to "Cancel", creadit2, class: 'button' %>
    </p>
  </fieldset>
<% end %>

app/views/reviews/edit.html.erb
<header id="content-header">
  <h1>Editing <%= @reviews.name %> 's Review</h1>
</header>

<%= render 'form', creadit: 'Update' , creadit2: movie_reviews_path(@movie) %>

app/views/reviews/index.html.erb
<header id="content-header">
  <h1>Reviews for <%= link_to(@movie.title, @movie) %></h1>
</header>
<h3>Average Review</h3>
<p>
  <%= format_average_stars(@movie) %>
</p>
  <%= link_to "Write Review", 
  new_movie_review_path(@movie), 
  class: 'button ok review' %>
<br>
<ol id="reviews">
  <% @reviews.each do |review| %>
    <li>
      <span class="review">
      	<%= image_tag(review.stars.to_s + '_stars.png') %></span>
      <span class="user">by <%= review.name %></span>
      
      <%= link_to edit_review_image,
      [:edit, @movie, review]  %>
      
      <%= link_to delete_review_image, [@movie, review],
        id: "#{dom_id(review)}_delete",
        method: :delete, 
        data: { confirm: 'Are you sure?' } %>

      <span class="date"><%= time_ago_in_words(review.created_at) %> ago</span>
      <p>
        &quot;<%= review.comment %>&quot;
      </p>
    </li>
  <% end %>
</ol>

app/views/reviews/new.html.erb
<header id="content-header">
  <h1>Create a New Review</h1>
</header>


<%= render 'form', creadit: 'Create' , creadit2: @movie %>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
<section id="errors">
  <header>
    <h2>
      Oops! The <%= object.class.name %> could not be saved. 
    </h2>
    <h3>
      Please correct the following <%= pluralize(object.errors.count, "error") %>:
    </h3>
  </header>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
</section>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@users) do |f| %>
<%= render "shared/errors", object: @users %>
  <fieldset>
    <ol>
      <li class="required">
        <%= f.label :username %>
        <%= f.text_field :username, size: 40, 
        placeholder: "Alphanumeric characters only! No spaces dumbass" %>
      </li>
      <li class="required">
        <%= f.label :name %>
        <%= f.text_field :name, autofocus: true %>
      </li>
      <li class="required">
        <%= f.label :email %>
        <%= f.text_field :email %>
      </li>
      <li class="required">
        <%= f.label :password %>
        <%= f.password_field :password %>
      </li>
      <li class="required">
        <%= f.label :password_confirmation, "Confirm Password" %>
        <%= f.password_field :password_confirmation %>
      </li>
    </ol>

    <p>
      <% if @users.new_record? %>
          <%= f.submit "Create Account" %>
      <% else %>
          <%= f.submit "Update Account" %>
      <% end %>

      <%= link_to "Cancel", root_path, class: 'button' %>
    
    </p>

  </fieldset>
<% end %>

app/views/users/edit.html.erb
<header id="content-header">
  <h1>Editing <%= @users.name %></h1>
</header>

<%= render 'form' %>

app/views/users/index.html.erb
<header id="content-header">
  <h1><%= pluralize(@users.size, 'User') %></h1>
</header>

<ul id="users">
  <% @users.each do |user| %>
    <li>
      <%= link_to user.name, user %>   
    </li>
  <% end %>
</ul>

app/views/users/new.html.erb
<header id="content-header">
  <h1>Create a New Account</h1>
</header>

<%= render 'form' %>

app/views/users/show.html.erb
<article id="user">
  <header>
    <h1><%= @users.name  %></h1>
    <h2><%= mail_to(@users.email) %></h2>
    <h3>Member Since</h3>
    <p>
    <%= @users.created_at.strftime("%B %Y") %>
    </p>
  </header>

<footer>
   <nav>
      <% if current_user?(@users) || logged_admin? %>
      <%= link_to 'Edit Account', edit_user_path(@users),
         class: 'button' %>

      <%= link_to 'Delete Account', @users, 
         class: 'button',
         method: :delete, data: { confirm: 
         'Are you sure you want to delete your account? I am so sad to see you go' } %>
      <% end %>

   </nav>
  </footer>

</article>